### ISSUE TITLE
Address outstanding Testing / CI issues

### ISSUE THREAD

**Issue by cicorias** [thaliproject/salti-admin#3]
- [ ] Could you please set up something like Travis to automatically test the code on each check in and put a badge in GitHub to tell us if tests are passing?
  TODO
- [ ] In test-basic.js I would expect a test to confirm that the buffer is the right size. You can expose the default buffer size as a property on the static newable object (e.g. admin.defaultSecretSizeInBytes or admin.prototype.defaultSecretSizeInBytes, for no good reason I tend to have a preference for the former over the later). I would also expect a test showing that setSecret works although if you adopt my proposal above you won't need that.
  TODO:
- [ ] Just for chuckles I would include at least one request with a request body and see that it is both properly accepted and rejected.
  TODO:

**Comment by cicorias** [comment]
- [X] Could you please set up something like Travis to automatically test the code on each check in and put a badge in GitHub to tell us if tests are passing?

> updated and green
> - [ ] In test-basic.js I would expect a test to confirm that the buffer is the right size. You can expose the default buffer size as a property on the static newable object (e.g. admin.defaultSecretSizeInBytes or admin.prototype.defaultSecretSizeInBytes, for no good reason I tend to have a preference for the former over the later). I would also expect a test showing that setSecret works although if you adopt my proposal above you won't need that.
> 
> TODO:
- [ ] Just for chuckles I would include at least one request with a request body and see that it is both properly accepted and rejected. 

> TODO:

**Comment by yaronyg** [comment]
@cicorias can we close this since you have submitted a PR that resolves it? Generally once the PR goes out we close the associated issue and let an remaining problems be resolved with the PR.
